version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: autonova_db
    environment:
      POSTGRES_USER: autonova_user
      POSTGRES_PASSWORD: autonova_password
      POSTGRES_DB: autonova_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
